version: '3.9'

services:
  postgis14:
    image: kartoza/postgis:14-3.3--v2022.07.22
    restart: always
    environment:
      POSTGRES_DBNAME: propine_assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'